# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Acceptance Tests

on:
  push:
    branches:
      - main
      - master

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run lint

  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: |
          npm i
          npm run build
      - name: Run tests
        working-directory: ./test
        run: |
          npm i
          npm run test && npm run allure-reports-generate && npm run allure-reports-patch
        env:
          MAILINATOR_TOKEN: ${{secrets.MAILINATOR_TOKEN}}
          MAILINATOR_DOMAIN: ${{secrets.MAILINATOR_DOMAIN}}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-reports
          path: |
            ./test/output/allure-reports/*
      - name: Allure reports 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./test/output/allure-reports
